language: node_js

node_js:
  - "stable"

sudo: false

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run lint:scripts
  - npm run lint:styles
  - npm run lint:templates

branches:
  only:
    - master
