module.exports =
	appImages: 'app/images'
	appStylesHelpers: 'app/styles/helpers'
	dist: 'dist'
	assets: 'dist/assets/'
	images: 'dist/assets/images'
	scripts: 'dist/assets/scripts'
	scriptsLibs: 'dist/assets/scripts/libs'
	styles: 'dist/assets/styles'
